### ISSUE TITLE
Repeated marque

### ISSUE THREAD

**Issue by OskarMast** [OskarMast/my-portfolio#7]
I want to know the method how to implement repeated marque

**Comment by dancerking** [comment]
You can use CSS without using Javascript.
```html
<div>
  <div className="marquee-group flex shrink-0 items-center justify-around gap-7 md:gap-12 min-w-full"></div>
  <div className="marquee-group flex shrink-0 items-center justify-around gap-7 md:gap-12 min-w-full"></div>
</div>
``` 
```css
.marquee-group {
    animation: scroll-left var(--duration) linear infinite;
}
@keyframes scroll-left {
    from {
        transform: translateX(var(--scroll-start));
    }
    to {
        transform: translateX(var(--scroll-end));
    }
}
@media (prefers-reduced-motion: reduce) {
    .marquee-group {
        animation-play-state: paused;
    }
}
:root {
    --gap: 2rem;
    --duration: 27s;
    --scroll-start: 0;
    --scroll-end: calc(-100% - var(--gap));
}
``` 
As you can see above code statement, you can implement repeated marquee by using CSS only.
I hope you will be good.
Thanks
